### ISSUE TITLE
ASAN error

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/lpSolve#25]
```
The error most likely occurred in:
> ### Name: optimal_dispersion
> ### Title: Maximize dispersion for K groups
> ### Aliases: optimal_dispersion
> 
> ### ** Examples
> 
> 
> N <- 30
> M <- 5
> K <- 3
> data <- matrix(rnorm(N*M), ncol = M)
> distances <- dist(data)
> 
> opt <- optimal_dispersion(distances, K = K)
```

```
=================================================================
==3780==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5180000903b0 at pc 0x7fe714b1f705 bp 0x7fff49dd59c0 sp 0x7fff49dd59b8
READ of size 8 at 0x5180000903b0 thread T0
    #0 0x7fe714b1f704 in my_idamax /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/myblas.c:662:18
    #1 0x7fe714b20f17 in idamaxlpsolve /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/myblas.c:635:12
    #2 0x7fe7149b1[98](https://github.com/gaborcsardi/anticlust/actions/runs/12317821650/job/34381161155#step:6:102)8 in initialize_solution /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_lib.c:9159:7
    #3 0x7fe7149b2050 in recompute_solution /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_lib.c:9171:3
    #4 0x7fe7149dc945 in invert /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_matrix.c:2650:3
    #5 0x7fe714aa6198 in spx_run /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_simplex.c:1555:7
    #6 0x7fe7149f0247 in solve_LP /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_mipbb.c:795:14
    #7 0x7fe7149f52bf in solve_BB /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_mipbb.c:1258:12
    #8 0x7fe7149f62a5 in run_BB /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_mipbb.c:1351:14
    #9 0x7fe714aabcd6 in spx_solve /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_simplex.c:2055:14
    #10 0x7fe714aad35f in lin_solve /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_simplex.c:2154:12
    #11 0x7fe714abdc6b in lpslink /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lpslink56.c:381:25
...
```

```
0x5180000903b0 is located 0 bytes after 816-byte region [0x518000090080,0x5180000903b0)
allocated by thread T0 here:
    #0 0x55d9a7c2f9dc in realloc (/opt/R/devel-asan/lib/R/bin/exec/R+0xcb9dc) (BuildId: 6c8cf8c41ad25c011ef63671f4668d93b5d58e3c)
    #1 0x7fe714aae4b2 in allocLREAL /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_utils.c:116:22
    #2 0x7fe714954f62 in inc_row_space /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_lib.c:2684:9
    #3 0x7fe71494b030 in make_lp /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lp_lib.c:[144](https://github.com/gaborcsardi/anticlust/actions/runs/12317821650/job/34381161155#step:6:148)8:3
    #4 0x7fe714abd20c in lpslink /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/lpslink56.c:283:6
    #5 0x7fe7402e72ee in do_dotCode /tmp/R-devel/src/main/dotcode.c
```

```
SUMMARY: AddressSanitizer: heap-buffer-overflow /tmp/Rtmp1wKVfo/R.INSTALL64022ab5566/lpSolve/src/myblas.c:662:18 in my_idamax
Shadow bytes around the buggy address:
  0x518000090100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x518000090180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x518000090200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x518000090280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x518000090300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x518000090380: 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa
  0x518000090400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x518000090480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x518000090500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x518000090580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x518000090600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3780==ABORTING
```
https://github.com/gaborcsardi/anticlust/actions/runs/12317821650/job/34381161155

**Comment by gaborcsardi** [comment]
Reprex:
```
library('anticlust')

RNGkind("default", "default", "default")
set.seed(1)

N <- 30
M <- 5
K <- 3
data <- matrix(rnorm(N*M), ncol = M)
distances <- dist(data)

opt <- optimal_dispersion(distances, K = K)
opt
```

**Comment by gaborcsardi** [comment]
Seems like a bug that is triggered when there is no BLAS available and polyfills are used instead, and idamax and idamin have an off by one error.

**Comment by gaborcsardi** [comment]
Seems to work: https://github.com/gaborcsardi/anticlust/actions/runs/12321011585/job/34391521381

**Comment by gaborcsardi** [comment]
Now it is really fixed: https://github.com/gaborcsardi/anticlust/actions/runs/12323613649/job/34399581535

**Comment by gaborcsardi** [comment]
New release happening at #26.
